import type {
  PaymentMethod,
  BillingHistory,
  MemberSubscription,
  SubscriptionPlan,
} from "@/@types/subscription";

export const MOCK_MEMBER_SUBSCRIPTION: MemberSubscription = {
  currentPlan: "explorer",
  billingPeriod: "month",
  renewalDate: "2026-04-30",
  isActive: true,
  usage: {
    periodStart: "2026-03-30",
    periodEnd: "2026-04-30",
    cvAnalysisUsed: 2,
    cvAnalysisLimit: 3,
    jobSearchUsed: 0,
    jobSearchLimit: 1,
    jobResultsPerSearch: 5,
    interviewUsed: 1,
    interviewLimit: 1,
    autoApplyUsed: 0,
    autoApplyLimit: 0,
    cvVersionsStored: 1,
    cvVersionsLimit: 1,
  },
};

export const MOCK_PLANS: SubscriptionPlan[] = [
  {
    id: "explorer",
    name: "Explorer",
    price: 0,
    billingPeriod: "month",
    features: [
      "3 CV analyses/month",
      "1 mock interview/month",
      "1 job search set (5 results)",
      "0 auto-apply",
      "1 CV version stored",
    ],
    cvAnalysisLimit: 3,
    jobSearchLimit: 1,
    jobResultsPerSearch: 5,
    interviewLimit: 1,
    autoApplyLimit: 0,
    cvVersionsLimit: 1,
  },
  {
    id: "strategist",
    name: "Strategist",
    price: 12,
    billingPeriod: "month",
    features: [
      "20 CV analyses/month",
      "15 mock interviews/month",
      "10 job search sets (20 results)",
      "10 auto-applications/month",
      "5 CV versions stored",
    ],
    isPopular: true,
    cvAnalysisLimit: 20,
    jobSearchLimit: 10,
    jobResultsPerSearch: 20,
    interviewLimit: 15,
    autoApplyLimit: 10,
    cvVersionsLimit: 5,
  },
  {
    id: "architect",
    name: "Architect",
    price: 29,
    billingPeriod: "month",
    features: [
      "Unlimited CV analyses",
      "Unlimited mock interviews",
      "Unlimited job searches",
      "Unlimited auto-applications",
      "Unlimited CV versions",
    ],
    cvAnalysisLimit: -1,
    jobSearchLimit: -1,
    jobResultsPerSearch: -1,
    interviewLimit: -1,
    autoApplyLimit: -1,
    cvVersionsLimit: -1,
  },
  {
    id: "explorer",
    name: "Explorer",
    price: 0,
    billingPeriod: "year",
    features: [
      "3 CV analyses/month",
      "1 mock interview/month",
      "1 job search set (5 results)",
      "0 auto-apply",
      "1 CV version stored",
    ],
    cvAnalysisLimit: 3,
    jobSearchLimit: 1,
    jobResultsPerSearch: 5,
    interviewLimit: 1,
    autoApplyLimit: 0,
    cvVersionsLimit: 1,
  },
  {
    id: "strategist",
    name: "Strategist",
    price: 115,
    billingPeriod: "year",
    features: [
      "20 CV analyses/month",
      "15 mock interviews/month",
      "10 job search sets (20 results)",
      "10 auto-applications/month",
      "5 CV versions stored",
      "Save $29 per year",
    ],
    isPopular: true,
    cvAnalysisLimit: 20,
    jobSearchLimit: 10,
    jobResultsPerSearch: 20,
    interviewLimit: 15,
    autoApplyLimit: 10,
    cvVersionsLimit: 5,
  },
  {
    id: "architect",
    name: "Architect",
    price: 278,
    billingPeriod: "year",
    features: [
      "Unlimited CV analyses",
      "Unlimited mock interviews",
      "Unlimited job searches",
      "Unlimited auto-applications",
      "Unlimited CV versions",
      "Save $70 per year",
    ],
    cvAnalysisLimit: -1,
    jobSearchLimit: -1,
    jobResultsPerSearch: -1,
    interviewLimit: -1,
    autoApplyLimit: -1,
    cvVersionsLimit: -1,
  },
];

export const MOCK_BILLING_HISTORY: BillingHistory[] = [
  {
    id: "inv_001",
    date: "2026-02-14",
    amount: 29.0,
    status: "paid",
    invoice: "/invoices/inv_001.pdf",
  },
  {
    id: "inv_002",
    date: "2026-01-14",
    amount: 29.0,
    status: "paid",
    invoice: "/invoices/inv_002.pdf",
  },
  {
    id: "inv_003",
    date: "2025-12-14",
    amount: 29.0,
    status: "paid",
    invoice: "/invoices/inv_003.pdf",
  },
];

export const MOCK_PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: "pm_001",
    type: "card",
    last4: "4242",
    brand: "Visa",
    expiryMonth: 12,
    expiryYear: 2027,
    isDefault: true,
  },
  {
    id: "pm_002",
    type: "card",
    last4: "5555",
    brand: "Mastercard",
    expiryMonth: 8,
    expiryYear: 2026,
    isDefault: false,
  },
];
