import type {
  PaymentMethod,
  BillingHistory,
  MemberSubscription,
  SubscriptionPlan,
} from "@/@types/subscription";

export const MOCK_MEMBER_SUBSCRIPTION: MemberSubscription = {
  currentPlan: "explorer",
  billingPeriod: "month",
  renewalDate: "2026-03-14",
  isActive: true,
  usage: {
    agentsUsed: 3,
    jobsApplied: 47,
  },
};

export const MOCK_PLANS: SubscriptionPlan[] = [
  {
    id: "explorer",
    name: "Explorer",
    price: 0,
    billingPeriod: "month",
    features: [
      "3 CV analyses/month (basic single-pass)",
      "1 mock interview session/month (text only)",
      "1 job search set (5 results)",
      "0 auto-apply",
      "Manual job description input only",
      "1 CV version stored",
    ],
    maxAgents: 1,
    maxJobs: 10,
  },
  {
    id: "strategist",
    name: "Strategist",
    price: 12,
    billingPeriod: "month",
    features: [
      "20 CV analyses/month (multi-agent advanced)",
      "15 mock interview sessions/month (voice enabled via TTS)",
      "10 job search sets (20 results each)",
      "10 auto-applications/month",
      "AI CV rewriting per job (Refinement Swarm)",
      "5 CV versions stored",
      "Agent transparency (React Flow visualization)",
    ],
    isPopular: true,
    maxAgents: 5,
    maxJobs: 10,
  },
  {
    id: "architect",
    name: "Architect",
    price: 29,
    billingPeriod: "month",
    features: [
      "Unlimited CV analyses (advanced multi-agent)",
      "Unlimited mock interviews (voice + priority processing)",
      "Unlimited job search sets (50 results each)",
      "Unlimited auto-applications",
      "Priority AI queue (faster responses)",
      "Unlimited CV versions stored",
      "Full agent transparency",
      "Early access to new features",
    ],
  },
  {
    id: "explorer",
    name: "Explorer",
    price: 0,
    billingPeriod: "year",
    features: [
      "3 CV analyses/month (basic single-pass)",
      "1 mock interview session/month (text only)",
      "1 job search set (5 results)",
      "0 auto-apply",
      "Manual job description input only",
      "1 CV version stored",
    ],
    maxAgents: 1,
    maxJobs: 10,
  },
  {
    id: "strategist",
    name: "Strategist",
    price: 115,
    billingPeriod: "year",
    features: [
      "20 CV analyses/month (multi-agent advanced)",
      "15 mock interview sessions/month (voice enabled via TTS)",
      "10 job search sets (20 results each)",
      "10 auto-applications/month",
      "AI CV rewriting per job (Refinement Swarm)",
      "5 CV versions stored",
      "Agent transparency (React Flow visualization)",
      "Save $29 per year",
    ],
    isPopular: true,
    maxAgents: 5,
    maxJobs: 10,
  },
  {
    id: "architect",
    name: "Architect",
    price: 278,
    billingPeriod: "year",
    features: [
      "Unlimited CV analyses (advanced multi-agent)",
      "Unlimited mock interviews (voice + priority processing)",
      "Unlimited job search sets (50 results each)",
      "Unlimited auto-applications",
      "Priority AI queue (faster responses)",
      "Unlimited CV versions stored",
      "Full agent transparency",
      "Early access to new features",
      "Save $70 per year",
    ],
  },
];

export const MOCK_BILLING_HISTORY: BillingHistory[] = [
  {
    id: "inv_001",
    date: "2026-02-14",
    amount: 29.0,
    status: "paid",
    invoice: "/invoices/inv_001.pdf",
  },
  {
    id: "inv_002",
    date: "2026-01-14",
    amount: 29.0,
    status: "paid",
    invoice: "/invoices/inv_002.pdf",
  },
  {
    id: "inv_003",
    date: "2025-12-14",
    amount: 29.0,
    status: "paid",
    invoice: "/invoices/inv_003.pdf",
  },
];

export const MOCK_PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: "pm_001",
    type: "card",
    last4: "4242",
    brand: "Visa",
    expiryMonth: 12,
    expiryYear: 2027,
    isDefault: true,
  },
  {
    id: "pm_002",
    type: "card",
    last4: "5555",
    brand: "Mastercard",
    expiryMonth: 8,
    expiryYear: 2026,
    isDefault: false,
  },
];
