spring.application.name=arcaive-backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

server.servlet.session.cookie.http-only=true
server.reactive.session.cookie.same-site=strict
server.servlet.session.cookie.secure=true

livekit.api-key=${LIVEKIT_API_KEY}
livekit.api-secret=${LIVEKIT_API_SECRET}
livekit.url=${LIVEKIT_URL}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.timeout=2000ms

rate-limit.capacity=10
rate-limit.refill-tokens=1
rate-limit.refill-duration-seconds=1