export const COMMON_ROLE_SUGGESTIONS: string[] = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "Full-Stack Engineer",
  "Full-Stack Developer",
  "Backend Developer",
  "Frontend Developer",
  "Software Developer",
  "Junior Software Developer",
  "Mid-Level Software Engineer",
  "Lead Software Engineer",
  "Web Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "React Native Developer",
  "Flutter Developer",
  "Java Developer",
  "Senior Java Developer",
  "Java Backend Developer",
  "Spring Boot Developer",
  "Java Software Engineer",
  "Enterprise Java Developer",
  "Node.js Developer",
  "TypeScript Developer",
  "JavaScript Developer",
  "React Developer",
  "Angular Developer",
  "Vue.js Developer",
  "Next.js Developer",
  "Python Developer",
  "Python Backend Developer",
  "Django Developer",
  "FastAPI Developer",
  "Cloud Engineer",
  "Cloud Architect",
  "AWS Solutions Architect",
  "Azure Cloud Engineer",
  "GCP Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",
  "Site Reliability Engineer (SRE)",
  "DevOps Engineer",
  "DevSecOps Engineer",
  "MLOps Engineer",
  "Data Engineer",
  "Senior Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Senior Machine Learning Engineer",
  "AI Engineer",
  "AI/ML Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Deep Learning Engineer",
  "Applied AI Scientist",
  "Research Engineer",
  "LLM Engineer",
  "Generative AI Engineer",
  "Data Analyst",
  "Business Intelligence Analyst",
  "BI Developer",
  "Analytics Engineer",
  "Solutions Architect",
  "Enterprise Architect",
  "Software Architect",
  "Technical Architect",
  "System Architect",
  "Security Engineer",
  "Application Security Engineer",
  "Cybersecurity Analyst",
  "Penetration Tester",
  "Security Architect",
  "Information Security Analyst",
  "QA Engineer",
  "Software Test Engineer",
  "Automation Test Engineer",
  "QA Automation Engineer",
  "SDET (Software Development Engineer in Test)",
  "Embedded Systems Engineer",
  "Firmware Engineer",
  "Systems Engineer",
  "C++ Developer",
  "Rust Developer",
  "Database Administrator",
  "Database Engineer",
  "Database Developer",
  "Product Manager",
  "Senior Product Manager",
  "Technical Product Manager",
  "Product Owner",
  "Engineering Manager",
  "Software Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "CTO",
  "Technical Lead",
  "Tech Lead",
  "UI/UX Designer",
  "UX Designer",
  "Product Designer",
  "UI Designer",
  "Frontend Designer",
  "Interaction Designer",
  "Research Scientist",
  "Research Engineer",
  "Applied Scientist",
  "Game Developer",
  "Unity Developer",
  "Unreal Engine Developer",
  "Game Engine Engineer",
  "Blockchain Developer",
  "Smart Contract Developer",
  "Web3 Engineer",
  "Solidity Developer",
  "Technical Consultant",
  "Solutions Engineer",
  "Implementation Engineer",
  "Integration Engineer",
  "API Developer",
  "Microservices Engineer",
  "Kubernetes Engineer",
  "Automation Engineer",
  "Robotics Engineer",
  "Project Manager",
  "Scrum Master",
  "Business Analyst",
  "Technical Writer",
  "IT Support Engineer",
  "IT Consultant",
];
